#!/usr/bin/env perl
use lib 'lib';
use GitInsight;
use GitInsight::Util qw(info error warning prob);
use Data::Dumper;
use Getopt::Long;
my ($no_day_stats,$username);

GetOptions (
            "username=s"   => \$username,      # string
            "nodaystats"  => \$no_day_stats)   # flag
or die("Error in command line arguments\n");

die ("At least you must enter a github username") if !$username;

my $Insight= GitInsight->new(no_day_stats=>$no_day_stats);
$Insight->contrib_calendar($username);
$Insight->process;